[package]
name = "crossme"
version = "0.1.0"
authors = ["Nicolas Viennot <nicolas@viennot.biz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
